/*
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lockally.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lockally.sdk.model.AuditEvent;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.lockally.sdk.JSON;

/**
 * GetAuditSummary200Response
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-02T21:47:01.311129+01:00[Africa/Lagos]", comments = "Generator version: 7.23.0")
public class GetAuditSummary200Response {
  public static final String SERIALIZED_NAME_ADMIN_ACTIONS_TODAY = "admin_actions_today";
  @SerializedName(SERIALIZED_NAME_ADMIN_ACTIONS_TODAY)
  @jakarta.annotation.Nullable
  private Integer adminActionsToday;

  public static final String SERIALIZED_NAME_RECENT_LOGINS = "recent_logins";
  @SerializedName(SERIALIZED_NAME_RECENT_LOGINS)
  @jakarta.annotation.Nullable
  private List<AuditEvent> recentLogins = new ArrayList<>();

  public static final String SERIALIZED_NAME_RECENT_EXPORTS = "recent_exports";
  @SerializedName(SERIALIZED_NAME_RECENT_EXPORTS)
  @jakarta.annotation.Nullable
  private List<AuditEvent> recentExports = new ArrayList<>();

  public static final String SERIALIZED_NAME_DELETED_MAILBOXES = "deleted_mailboxes";
  @SerializedName(SERIALIZED_NAME_DELETED_MAILBOXES)
  @jakarta.annotation.Nullable
  private List<AuditEvent> deletedMailboxes = new ArrayList<>();

  public static final String SERIALIZED_NAME_GENERATED_AT = "generated_at";
  @SerializedName(SERIALIZED_NAME_GENERATED_AT)
  @jakarta.annotation.Nullable
  private OffsetDateTime generatedAt;

  public GetAuditSummary200Response() {
  }

  public GetAuditSummary200Response adminActionsToday(@jakarta.annotation.Nullable Integer adminActionsToday) {
    this.adminActionsToday = adminActionsToday;
    return this;
  }

  /**
   * Get adminActionsToday
   * @return adminActionsToday
   */
  @jakarta.annotation.Nullable
  public Integer getAdminActionsToday() {
    return adminActionsToday;
  }

  public void setAdminActionsToday(@jakarta.annotation.Nullable Integer adminActionsToday) {
    this.adminActionsToday = adminActionsToday;
  }


  public GetAuditSummary200Response recentLogins(@jakarta.annotation.Nullable List<AuditEvent> recentLogins) {
    this.recentLogins = recentLogins;
    return this;
  }

  public GetAuditSummary200Response addRecentLoginsItem(AuditEvent recentLoginsItem) {
    if (this.recentLogins == null) {
      this.recentLogins = new ArrayList<>();
    }
    this.recentLogins.add(recentLoginsItem);
    return this;
  }

  /**
   * Get recentLogins
   * @return recentLogins
   */
  @jakarta.annotation.Nullable
  public List<AuditEvent> getRecentLogins() {
    return recentLogins;
  }

  public void setRecentLogins(@jakarta.annotation.Nullable List<AuditEvent> recentLogins) {
    this.recentLogins = recentLogins;
  }


  public GetAuditSummary200Response recentExports(@jakarta.annotation.Nullable List<AuditEvent> recentExports) {
    this.recentExports = recentExports;
    return this;
  }

  public GetAuditSummary200Response addRecentExportsItem(AuditEvent recentExportsItem) {
    if (this.recentExports == null) {
      this.recentExports = new ArrayList<>();
    }
    this.recentExports.add(recentExportsItem);
    return this;
  }

  /**
   * Get recentExports
   * @return recentExports
   */
  @jakarta.annotation.Nullable
  public List<AuditEvent> getRecentExports() {
    return recentExports;
  }

  public void setRecentExports(@jakarta.annotation.Nullable List<AuditEvent> recentExports) {
    this.recentExports = recentExports;
  }


  public GetAuditSummary200Response deletedMailboxes(@jakarta.annotation.Nullable List<AuditEvent> deletedMailboxes) {
    this.deletedMailboxes = deletedMailboxes;
    return this;
  }

  public GetAuditSummary200Response addDeletedMailboxesItem(AuditEvent deletedMailboxesItem) {
    if (this.deletedMailboxes == null) {
      this.deletedMailboxes = new ArrayList<>();
    }
    this.deletedMailboxes.add(deletedMailboxesItem);
    return this;
  }

  /**
   * Get deletedMailboxes
   * @return deletedMailboxes
   */
  @jakarta.annotation.Nullable
  public List<AuditEvent> getDeletedMailboxes() {
    return deletedMailboxes;
  }

  public void setDeletedMailboxes(@jakarta.annotation.Nullable List<AuditEvent> deletedMailboxes) {
    this.deletedMailboxes = deletedMailboxes;
  }


  public GetAuditSummary200Response generatedAt(@jakarta.annotation.Nullable OffsetDateTime generatedAt) {
    this.generatedAt = generatedAt;
    return this;
  }

  /**
   * Get generatedAt
   * @return generatedAt
   */
  @jakarta.annotation.Nullable
  public OffsetDateTime getGeneratedAt() {
    return generatedAt;
  }

  public void setGeneratedAt(@jakarta.annotation.Nullable OffsetDateTime generatedAt) {
    this.generatedAt = generatedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAuditSummary200Response getAuditSummary200Response = (GetAuditSummary200Response) o;
    return Objects.equals(this.adminActionsToday, getAuditSummary200Response.adminActionsToday) &&
        Objects.equals(this.recentLogins, getAuditSummary200Response.recentLogins) &&
        Objects.equals(this.recentExports, getAuditSummary200Response.recentExports) &&
        Objects.equals(this.deletedMailboxes, getAuditSummary200Response.deletedMailboxes) &&
        Objects.equals(this.generatedAt, getAuditSummary200Response.generatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adminActionsToday, recentLogins, recentExports, deletedMailboxes, generatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAuditSummary200Response {\n");
    sb.append("    adminActionsToday: ").append(toIndentedString(adminActionsToday)).append("\n");
    sb.append("    recentLogins: ").append(toIndentedString(recentLogins)).append("\n");
    sb.append("    recentExports: ").append(toIndentedString(recentExports)).append("\n");
    sb.append("    deletedMailboxes: ").append(toIndentedString(deletedMailboxes)).append("\n");
    sb.append("    generatedAt: ").append(toIndentedString(generatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("admin_actions_today", "recent_logins", "recent_exports", "deleted_mailboxes", "generated_at"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetAuditSummary200Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetAuditSummary200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in GetAuditSummary200Response is not found in the empty JSON string", GetAuditSummary200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetAuditSummary200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetAuditSummary200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("recent_logins") != null && !jsonObj.get("recent_logins").isJsonNull()) {
        JsonArray jsonArrayrecentLogins = jsonObj.getAsJsonArray("recent_logins");
        if (jsonArrayrecentLogins != null) {
          // ensure the json data is an array
          if (!jsonObj.get("recent_logins").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `recent_logins` to be an array in the JSON string but got `%s`", jsonObj.get("recent_logins").toString()));
          }

          // validate the optional field `recent_logins` (array)
          for (int i = 0; i < jsonArrayrecentLogins.size(); i++) {
            AuditEvent.validateJsonElement(jsonArrayrecentLogins.get(i));
          };
        }
      }
      if (jsonObj.get("recent_exports") != null && !jsonObj.get("recent_exports").isJsonNull()) {
        JsonArray jsonArrayrecentExports = jsonObj.getAsJsonArray("recent_exports");
        if (jsonArrayrecentExports != null) {
          // ensure the json data is an array
          if (!jsonObj.get("recent_exports").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `recent_exports` to be an array in the JSON string but got `%s`", jsonObj.get("recent_exports").toString()));
          }

          // validate the optional field `recent_exports` (array)
          for (int i = 0; i < jsonArrayrecentExports.size(); i++) {
            AuditEvent.validateJsonElement(jsonArrayrecentExports.get(i));
          };
        }
      }
      if (jsonObj.get("deleted_mailboxes") != null && !jsonObj.get("deleted_mailboxes").isJsonNull()) {
        JsonArray jsonArraydeletedMailboxes = jsonObj.getAsJsonArray("deleted_mailboxes");
        if (jsonArraydeletedMailboxes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("deleted_mailboxes").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `deleted_mailboxes` to be an array in the JSON string but got `%s`", jsonObj.get("deleted_mailboxes").toString()));
          }

          // validate the optional field `deleted_mailboxes` (array)
          for (int i = 0; i < jsonArraydeletedMailboxes.size(); i++) {
            AuditEvent.validateJsonElement(jsonArraydeletedMailboxes.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetAuditSummary200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetAuditSummary200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetAuditSummary200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetAuditSummary200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<GetAuditSummary200Response>() {
           @Override
           public void write(JsonWriter out, GetAuditSummary200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetAuditSummary200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetAuditSummary200Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetAuditSummary200Response
   * @throws IOException if the JSON string is invalid with respect to GetAuditSummary200Response
   */
  public static GetAuditSummary200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetAuditSummary200Response.class);
  }

  /**
   * Convert an instance of GetAuditSummary200Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

