/*
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lockally.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lockally.sdk.model.GetCalendarSecurity200ResponseAlertsInner;
import com.lockally.sdk.model.GetCalendarSecurity200ResponseDelegatedAccessInner;
import com.lockally.sdk.model.GetCalendarSecurity200ResponseExternalSharing;
import com.lockally.sdk.model.GetCalendarSecurity200ResponsePublicCalendarListInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.lockally.sdk.JSON;

/**
 * GetCalendarSecurity200Response
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-02T21:47:01.311129+01:00[Africa/Lagos]", comments = "Generator version: 7.23.0")
public class GetCalendarSecurity200Response {
  public static final String SERIALIZED_NAME_TOTAL_CALENDARS = "total_calendars";
  @SerializedName(SERIALIZED_NAME_TOTAL_CALENDARS)
  @jakarta.annotation.Nullable
  private Integer totalCalendars;

  public static final String SERIALIZED_NAME_PUBLIC_CALENDARS = "public_calendars";
  @SerializedName(SERIALIZED_NAME_PUBLIC_CALENDARS)
  @jakarta.annotation.Nullable
  private Integer publicCalendars;

  public static final String SERIALIZED_NAME_PRIVATE_CALENDARS = "private_calendars";
  @SerializedName(SERIALIZED_NAME_PRIVATE_CALENDARS)
  @jakarta.annotation.Nullable
  private Integer privateCalendars;

  public static final String SERIALIZED_NAME_TOTAL_MEMBERS = "total_members";
  @SerializedName(SERIALIZED_NAME_TOTAL_MEMBERS)
  @jakarta.annotation.Nullable
  private Integer totalMembers;

  public static final String SERIALIZED_NAME_DELEGATED_ACCESS = "delegated_access";
  @SerializedName(SERIALIZED_NAME_DELEGATED_ACCESS)
  @jakarta.annotation.Nullable
  private List<GetCalendarSecurity200ResponseDelegatedAccessInner> delegatedAccess = new ArrayList<>();

  public static final String SERIALIZED_NAME_PUBLIC_CALENDAR_LIST = "public_calendar_list";
  @SerializedName(SERIALIZED_NAME_PUBLIC_CALENDAR_LIST)
  @jakarta.annotation.Nullable
  private List<GetCalendarSecurity200ResponsePublicCalendarListInner> publicCalendarList = new ArrayList<>();

  public static final String SERIALIZED_NAME_ALERTS = "alerts";
  @SerializedName(SERIALIZED_NAME_ALERTS)
  @jakarta.annotation.Nullable
  private List<GetCalendarSecurity200ResponseAlertsInner> alerts = new ArrayList<>();

  public static final String SERIALIZED_NAME_EXTERNAL_SHARING = "external_sharing";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_SHARING)
  @jakarta.annotation.Nullable
  private GetCalendarSecurity200ResponseExternalSharing externalSharing;

  public GetCalendarSecurity200Response() {
  }

  public GetCalendarSecurity200Response totalCalendars(@jakarta.annotation.Nullable Integer totalCalendars) {
    this.totalCalendars = totalCalendars;
    return this;
  }

  /**
   * Get totalCalendars
   * @return totalCalendars
   */
  @jakarta.annotation.Nullable
  public Integer getTotalCalendars() {
    return totalCalendars;
  }

  public void setTotalCalendars(@jakarta.annotation.Nullable Integer totalCalendars) {
    this.totalCalendars = totalCalendars;
  }


  public GetCalendarSecurity200Response publicCalendars(@jakarta.annotation.Nullable Integer publicCalendars) {
    this.publicCalendars = publicCalendars;
    return this;
  }

  /**
   * Get publicCalendars
   * @return publicCalendars
   */
  @jakarta.annotation.Nullable
  public Integer getPublicCalendars() {
    return publicCalendars;
  }

  public void setPublicCalendars(@jakarta.annotation.Nullable Integer publicCalendars) {
    this.publicCalendars = publicCalendars;
  }


  public GetCalendarSecurity200Response privateCalendars(@jakarta.annotation.Nullable Integer privateCalendars) {
    this.privateCalendars = privateCalendars;
    return this;
  }

  /**
   * Get privateCalendars
   * @return privateCalendars
   */
  @jakarta.annotation.Nullable
  public Integer getPrivateCalendars() {
    return privateCalendars;
  }

  public void setPrivateCalendars(@jakarta.annotation.Nullable Integer privateCalendars) {
    this.privateCalendars = privateCalendars;
  }


  public GetCalendarSecurity200Response totalMembers(@jakarta.annotation.Nullable Integer totalMembers) {
    this.totalMembers = totalMembers;
    return this;
  }

  /**
   * Get totalMembers
   * @return totalMembers
   */
  @jakarta.annotation.Nullable
  public Integer getTotalMembers() {
    return totalMembers;
  }

  public void setTotalMembers(@jakarta.annotation.Nullable Integer totalMembers) {
    this.totalMembers = totalMembers;
  }


  public GetCalendarSecurity200Response delegatedAccess(@jakarta.annotation.Nullable List<GetCalendarSecurity200ResponseDelegatedAccessInner> delegatedAccess) {
    this.delegatedAccess = delegatedAccess;
    return this;
  }

  public GetCalendarSecurity200Response addDelegatedAccessItem(GetCalendarSecurity200ResponseDelegatedAccessInner delegatedAccessItem) {
    if (this.delegatedAccess == null) {
      this.delegatedAccess = new ArrayList<>();
    }
    this.delegatedAccess.add(delegatedAccessItem);
    return this;
  }

  /**
   * Get delegatedAccess
   * @return delegatedAccess
   */
  @jakarta.annotation.Nullable
  public List<GetCalendarSecurity200ResponseDelegatedAccessInner> getDelegatedAccess() {
    return delegatedAccess;
  }

  public void setDelegatedAccess(@jakarta.annotation.Nullable List<GetCalendarSecurity200ResponseDelegatedAccessInner> delegatedAccess) {
    this.delegatedAccess = delegatedAccess;
  }


  public GetCalendarSecurity200Response publicCalendarList(@jakarta.annotation.Nullable List<GetCalendarSecurity200ResponsePublicCalendarListInner> publicCalendarList) {
    this.publicCalendarList = publicCalendarList;
    return this;
  }

  public GetCalendarSecurity200Response addPublicCalendarListItem(GetCalendarSecurity200ResponsePublicCalendarListInner publicCalendarListItem) {
    if (this.publicCalendarList == null) {
      this.publicCalendarList = new ArrayList<>();
    }
    this.publicCalendarList.add(publicCalendarListItem);
    return this;
  }

  /**
   * Get publicCalendarList
   * @return publicCalendarList
   */
  @jakarta.annotation.Nullable
  public List<GetCalendarSecurity200ResponsePublicCalendarListInner> getPublicCalendarList() {
    return publicCalendarList;
  }

  public void setPublicCalendarList(@jakarta.annotation.Nullable List<GetCalendarSecurity200ResponsePublicCalendarListInner> publicCalendarList) {
    this.publicCalendarList = publicCalendarList;
  }


  public GetCalendarSecurity200Response alerts(@jakarta.annotation.Nullable List<GetCalendarSecurity200ResponseAlertsInner> alerts) {
    this.alerts = alerts;
    return this;
  }

  public GetCalendarSecurity200Response addAlertsItem(GetCalendarSecurity200ResponseAlertsInner alertsItem) {
    if (this.alerts == null) {
      this.alerts = new ArrayList<>();
    }
    this.alerts.add(alertsItem);
    return this;
  }

  /**
   * Get alerts
   * @return alerts
   */
  @jakarta.annotation.Nullable
  public List<GetCalendarSecurity200ResponseAlertsInner> getAlerts() {
    return alerts;
  }

  public void setAlerts(@jakarta.annotation.Nullable List<GetCalendarSecurity200ResponseAlertsInner> alerts) {
    this.alerts = alerts;
  }


  public GetCalendarSecurity200Response externalSharing(@jakarta.annotation.Nullable GetCalendarSecurity200ResponseExternalSharing externalSharing) {
    this.externalSharing = externalSharing;
    return this;
  }

  /**
   * Get externalSharing
   * @return externalSharing
   */
  @jakarta.annotation.Nullable
  public GetCalendarSecurity200ResponseExternalSharing getExternalSharing() {
    return externalSharing;
  }

  public void setExternalSharing(@jakarta.annotation.Nullable GetCalendarSecurity200ResponseExternalSharing externalSharing) {
    this.externalSharing = externalSharing;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCalendarSecurity200Response getCalendarSecurity200Response = (GetCalendarSecurity200Response) o;
    return Objects.equals(this.totalCalendars, getCalendarSecurity200Response.totalCalendars) &&
        Objects.equals(this.publicCalendars, getCalendarSecurity200Response.publicCalendars) &&
        Objects.equals(this.privateCalendars, getCalendarSecurity200Response.privateCalendars) &&
        Objects.equals(this.totalMembers, getCalendarSecurity200Response.totalMembers) &&
        Objects.equals(this.delegatedAccess, getCalendarSecurity200Response.delegatedAccess) &&
        Objects.equals(this.publicCalendarList, getCalendarSecurity200Response.publicCalendarList) &&
        Objects.equals(this.alerts, getCalendarSecurity200Response.alerts) &&
        Objects.equals(this.externalSharing, getCalendarSecurity200Response.externalSharing);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalCalendars, publicCalendars, privateCalendars, totalMembers, delegatedAccess, publicCalendarList, alerts, externalSharing);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCalendarSecurity200Response {\n");
    sb.append("    totalCalendars: ").append(toIndentedString(totalCalendars)).append("\n");
    sb.append("    publicCalendars: ").append(toIndentedString(publicCalendars)).append("\n");
    sb.append("    privateCalendars: ").append(toIndentedString(privateCalendars)).append("\n");
    sb.append("    totalMembers: ").append(toIndentedString(totalMembers)).append("\n");
    sb.append("    delegatedAccess: ").append(toIndentedString(delegatedAccess)).append("\n");
    sb.append("    publicCalendarList: ").append(toIndentedString(publicCalendarList)).append("\n");
    sb.append("    alerts: ").append(toIndentedString(alerts)).append("\n");
    sb.append("    externalSharing: ").append(toIndentedString(externalSharing)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("total_calendars", "public_calendars", "private_calendars", "total_members", "delegated_access", "public_calendar_list", "alerts", "external_sharing"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetCalendarSecurity200Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetCalendarSecurity200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in GetCalendarSecurity200Response is not found in the empty JSON string", GetCalendarSecurity200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetCalendarSecurity200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetCalendarSecurity200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("delegated_access") != null && !jsonObj.get("delegated_access").isJsonNull()) {
        JsonArray jsonArraydelegatedAccess = jsonObj.getAsJsonArray("delegated_access");
        if (jsonArraydelegatedAccess != null) {
          // ensure the json data is an array
          if (!jsonObj.get("delegated_access").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `delegated_access` to be an array in the JSON string but got `%s`", jsonObj.get("delegated_access").toString()));
          }

          // validate the optional field `delegated_access` (array)
          for (int i = 0; i < jsonArraydelegatedAccess.size(); i++) {
            GetCalendarSecurity200ResponseDelegatedAccessInner.validateJsonElement(jsonArraydelegatedAccess.get(i));
          };
        }
      }
      if (jsonObj.get("public_calendar_list") != null && !jsonObj.get("public_calendar_list").isJsonNull()) {
        JsonArray jsonArraypublicCalendarList = jsonObj.getAsJsonArray("public_calendar_list");
        if (jsonArraypublicCalendarList != null) {
          // ensure the json data is an array
          if (!jsonObj.get("public_calendar_list").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `public_calendar_list` to be an array in the JSON string but got `%s`", jsonObj.get("public_calendar_list").toString()));
          }

          // validate the optional field `public_calendar_list` (array)
          for (int i = 0; i < jsonArraypublicCalendarList.size(); i++) {
            GetCalendarSecurity200ResponsePublicCalendarListInner.validateJsonElement(jsonArraypublicCalendarList.get(i));
          };
        }
      }
      if (jsonObj.get("alerts") != null && !jsonObj.get("alerts").isJsonNull()) {
        JsonArray jsonArrayalerts = jsonObj.getAsJsonArray("alerts");
        if (jsonArrayalerts != null) {
          // ensure the json data is an array
          if (!jsonObj.get("alerts").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `alerts` to be an array in the JSON string but got `%s`", jsonObj.get("alerts").toString()));
          }

          // validate the optional field `alerts` (array)
          for (int i = 0; i < jsonArrayalerts.size(); i++) {
            GetCalendarSecurity200ResponseAlertsInner.validateJsonElement(jsonArrayalerts.get(i));
          };
        }
      }
      // validate the optional field `external_sharing`
      if (jsonObj.get("external_sharing") != null && !jsonObj.get("external_sharing").isJsonNull()) {
        GetCalendarSecurity200ResponseExternalSharing.validateJsonElement(jsonObj.get("external_sharing"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetCalendarSecurity200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetCalendarSecurity200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetCalendarSecurity200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetCalendarSecurity200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<GetCalendarSecurity200Response>() {
           @Override
           public void write(JsonWriter out, GetCalendarSecurity200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetCalendarSecurity200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetCalendarSecurity200Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetCalendarSecurity200Response
   * @throws IOException if the JSON string is invalid with respect to GetCalendarSecurity200Response
   */
  public static GetCalendarSecurity200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetCalendarSecurity200Response.class);
  }

  /**
   * Convert an instance of GetCalendarSecurity200Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

