/*
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lockally.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.lockally.sdk.JSON;

/**
 * MessageStatsRates
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-02T21:47:01.311129+01:00[Africa/Lagos]", comments = "Generator version: 7.23.0")
public class MessageStatsRates {
  public static final String SERIALIZED_NAME_DELIVERED = "delivered";
  @SerializedName(SERIALIZED_NAME_DELIVERED)
  @jakarta.annotation.Nullable
  private Float delivered;

  public static final String SERIALIZED_NAME_BOUNCED = "bounced";
  @SerializedName(SERIALIZED_NAME_BOUNCED)
  @jakarta.annotation.Nullable
  private Float bounced;

  public static final String SERIALIZED_NAME_DEFERRED = "deferred";
  @SerializedName(SERIALIZED_NAME_DEFERRED)
  @jakarta.annotation.Nullable
  private Float deferred;

  public static final String SERIALIZED_NAME_COMPLAINT = "complaint";
  @SerializedName(SERIALIZED_NAME_COMPLAINT)
  @jakarta.annotation.Nullable
  private Float complaint;

  public MessageStatsRates() {
  }

  public MessageStatsRates delivered(@jakarta.annotation.Nullable Float delivered) {
    this.delivered = delivered;
    return this;
  }

  /**
   * Get delivered
   * @return delivered
   */
  @jakarta.annotation.Nullable
  public Float getDelivered() {
    return delivered;
  }

  public void setDelivered(@jakarta.annotation.Nullable Float delivered) {
    this.delivered = delivered;
  }


  public MessageStatsRates bounced(@jakarta.annotation.Nullable Float bounced) {
    this.bounced = bounced;
    return this;
  }

  /**
   * Get bounced
   * @return bounced
   */
  @jakarta.annotation.Nullable
  public Float getBounced() {
    return bounced;
  }

  public void setBounced(@jakarta.annotation.Nullable Float bounced) {
    this.bounced = bounced;
  }


  public MessageStatsRates deferred(@jakarta.annotation.Nullable Float deferred) {
    this.deferred = deferred;
    return this;
  }

  /**
   * Get deferred
   * @return deferred
   */
  @jakarta.annotation.Nullable
  public Float getDeferred() {
    return deferred;
  }

  public void setDeferred(@jakarta.annotation.Nullable Float deferred) {
    this.deferred = deferred;
  }


  public MessageStatsRates complaint(@jakarta.annotation.Nullable Float complaint) {
    this.complaint = complaint;
    return this;
  }

  /**
   * Get complaint
   * @return complaint
   */
  @jakarta.annotation.Nullable
  public Float getComplaint() {
    return complaint;
  }

  public void setComplaint(@jakarta.annotation.Nullable Float complaint) {
    this.complaint = complaint;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageStatsRates messageStatsRates = (MessageStatsRates) o;
    return Objects.equals(this.delivered, messageStatsRates.delivered) &&
        Objects.equals(this.bounced, messageStatsRates.bounced) &&
        Objects.equals(this.deferred, messageStatsRates.deferred) &&
        Objects.equals(this.complaint, messageStatsRates.complaint);
  }

  @Override
  public int hashCode() {
    return Objects.hash(delivered, bounced, deferred, complaint);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageStatsRates {\n");
    sb.append("    delivered: ").append(toIndentedString(delivered)).append("\n");
    sb.append("    bounced: ").append(toIndentedString(bounced)).append("\n");
    sb.append("    deferred: ").append(toIndentedString(deferred)).append("\n");
    sb.append("    complaint: ").append(toIndentedString(complaint)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("delivered", "bounced", "deferred", "complaint"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MessageStatsRates
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MessageStatsRates.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in MessageStatsRates is not found in the empty JSON string", MessageStatsRates.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MessageStatsRates.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `MessageStatsRates` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MessageStatsRates.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MessageStatsRates' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MessageStatsRates> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MessageStatsRates.class));

       return (TypeAdapter<T>) new TypeAdapter<MessageStatsRates>() {
           @Override
           public void write(JsonWriter out, MessageStatsRates value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MessageStatsRates read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MessageStatsRates given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MessageStatsRates
   * @throws IOException if the JSON string is invalid with respect to MessageStatsRates
   */
  public static MessageStatsRates fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MessageStatsRates.class);
  }

  /**
   * Convert an instance of MessageStatsRates to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

