/*
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lockally.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lockally.sdk.model.MigrationProgressMailboxesInner;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.lockally.sdk.JSON;

/**
 * MigrationProgress
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-02T21:47:01.311129+01:00[Africa/Lagos]", comments = "Generator version: 7.23.0")
public class MigrationProgress {
  public static final String SERIALIZED_NAME_MIGRATION_ID = "migration_id";
  @SerializedName(SERIALIZED_NAME_MIGRATION_ID)
  @jakarta.annotation.Nonnull
  private UUID migrationId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @jakarta.annotation.Nonnull
  private String status;

  public static final String SERIALIZED_NAME_TOTAL_MAILBOXES = "total_mailboxes";
  @SerializedName(SERIALIZED_NAME_TOTAL_MAILBOXES)
  @jakarta.annotation.Nonnull
  private Integer totalMailboxes;

  public static final String SERIALIZED_NAME_COMPLETED_MAILBOXES = "completed_mailboxes";
  @SerializedName(SERIALIZED_NAME_COMPLETED_MAILBOXES)
  @jakarta.annotation.Nonnull
  private Integer completedMailboxes;

  public static final String SERIALIZED_NAME_FAILED_MAILBOXES = "failed_mailboxes";
  @SerializedName(SERIALIZED_NAME_FAILED_MAILBOXES)
  @jakarta.annotation.Nonnull
  private Integer failedMailboxes;

  public static final String SERIALIZED_NAME_TOTAL_MESSAGES = "total_messages";
  @SerializedName(SERIALIZED_NAME_TOTAL_MESSAGES)
  @jakarta.annotation.Nonnull
  private Integer totalMessages;

  public static final String SERIALIZED_NAME_SYNCED_MESSAGES = "synced_messages";
  @SerializedName(SERIALIZED_NAME_SYNCED_MESSAGES)
  @jakarta.annotation.Nonnull
  private Integer syncedMessages;

  public static final String SERIALIZED_NAME_FAILED_MESSAGES = "failed_messages";
  @SerializedName(SERIALIZED_NAME_FAILED_MESSAGES)
  @jakarta.annotation.Nonnull
  private Integer failedMessages;

  public static final String SERIALIZED_NAME_PERCENT_COMPLETE = "percent_complete";
  @SerializedName(SERIALIZED_NAME_PERCENT_COMPLETE)
  @jakarta.annotation.Nonnull
  private BigDecimal percentComplete;

  public static final String SERIALIZED_NAME_MAILBOXES = "mailboxes";
  @SerializedName(SERIALIZED_NAME_MAILBOXES)
  @jakarta.annotation.Nonnull
  private List<MigrationProgressMailboxesInner> mailboxes = new ArrayList<>();

  public MigrationProgress() {
  }

  public MigrationProgress migrationId(@jakarta.annotation.Nonnull UUID migrationId) {
    this.migrationId = migrationId;
    return this;
  }

  /**
   * Get migrationId
   * @return migrationId
   */
  @jakarta.annotation.Nonnull
  public UUID getMigrationId() {
    return migrationId;
  }

  public void setMigrationId(@jakarta.annotation.Nonnull UUID migrationId) {
    this.migrationId = migrationId;
  }


  public MigrationProgress status(@jakarta.annotation.Nonnull String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  public String getStatus() {
    return status;
  }

  public void setStatus(@jakarta.annotation.Nonnull String status) {
    this.status = status;
  }


  public MigrationProgress totalMailboxes(@jakarta.annotation.Nonnull Integer totalMailboxes) {
    this.totalMailboxes = totalMailboxes;
    return this;
  }

  /**
   * Get totalMailboxes
   * @return totalMailboxes
   */
  @jakarta.annotation.Nonnull
  public Integer getTotalMailboxes() {
    return totalMailboxes;
  }

  public void setTotalMailboxes(@jakarta.annotation.Nonnull Integer totalMailboxes) {
    this.totalMailboxes = totalMailboxes;
  }


  public MigrationProgress completedMailboxes(@jakarta.annotation.Nonnull Integer completedMailboxes) {
    this.completedMailboxes = completedMailboxes;
    return this;
  }

  /**
   * Get completedMailboxes
   * @return completedMailboxes
   */
  @jakarta.annotation.Nonnull
  public Integer getCompletedMailboxes() {
    return completedMailboxes;
  }

  public void setCompletedMailboxes(@jakarta.annotation.Nonnull Integer completedMailboxes) {
    this.completedMailboxes = completedMailboxes;
  }


  public MigrationProgress failedMailboxes(@jakarta.annotation.Nonnull Integer failedMailboxes) {
    this.failedMailboxes = failedMailboxes;
    return this;
  }

  /**
   * Get failedMailboxes
   * @return failedMailboxes
   */
  @jakarta.annotation.Nonnull
  public Integer getFailedMailboxes() {
    return failedMailboxes;
  }

  public void setFailedMailboxes(@jakarta.annotation.Nonnull Integer failedMailboxes) {
    this.failedMailboxes = failedMailboxes;
  }


  public MigrationProgress totalMessages(@jakarta.annotation.Nonnull Integer totalMessages) {
    this.totalMessages = totalMessages;
    return this;
  }

  /**
   * Get totalMessages
   * @return totalMessages
   */
  @jakarta.annotation.Nonnull
  public Integer getTotalMessages() {
    return totalMessages;
  }

  public void setTotalMessages(@jakarta.annotation.Nonnull Integer totalMessages) {
    this.totalMessages = totalMessages;
  }


  public MigrationProgress syncedMessages(@jakarta.annotation.Nonnull Integer syncedMessages) {
    this.syncedMessages = syncedMessages;
    return this;
  }

  /**
   * Get syncedMessages
   * @return syncedMessages
   */
  @jakarta.annotation.Nonnull
  public Integer getSyncedMessages() {
    return syncedMessages;
  }

  public void setSyncedMessages(@jakarta.annotation.Nonnull Integer syncedMessages) {
    this.syncedMessages = syncedMessages;
  }


  public MigrationProgress failedMessages(@jakarta.annotation.Nonnull Integer failedMessages) {
    this.failedMessages = failedMessages;
    return this;
  }

  /**
   * Get failedMessages
   * @return failedMessages
   */
  @jakarta.annotation.Nonnull
  public Integer getFailedMessages() {
    return failedMessages;
  }

  public void setFailedMessages(@jakarta.annotation.Nonnull Integer failedMessages) {
    this.failedMessages = failedMessages;
  }


  public MigrationProgress percentComplete(@jakarta.annotation.Nonnull BigDecimal percentComplete) {
    this.percentComplete = percentComplete;
    return this;
  }

  /**
   * Get percentComplete
   * @return percentComplete
   */
  @jakarta.annotation.Nonnull
  public BigDecimal getPercentComplete() {
    return percentComplete;
  }

  public void setPercentComplete(@jakarta.annotation.Nonnull BigDecimal percentComplete) {
    this.percentComplete = percentComplete;
  }


  public MigrationProgress mailboxes(@jakarta.annotation.Nonnull List<MigrationProgressMailboxesInner> mailboxes) {
    this.mailboxes = mailboxes;
    return this;
  }

  public MigrationProgress addMailboxesItem(MigrationProgressMailboxesInner mailboxesItem) {
    if (this.mailboxes == null) {
      this.mailboxes = new ArrayList<>();
    }
    this.mailboxes.add(mailboxesItem);
    return this;
  }

  /**
   * Get mailboxes
   * @return mailboxes
   */
  @jakarta.annotation.Nonnull
  public List<MigrationProgressMailboxesInner> getMailboxes() {
    return mailboxes;
  }

  public void setMailboxes(@jakarta.annotation.Nonnull List<MigrationProgressMailboxesInner> mailboxes) {
    this.mailboxes = mailboxes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MigrationProgress migrationProgress = (MigrationProgress) o;
    return Objects.equals(this.migrationId, migrationProgress.migrationId) &&
        Objects.equals(this.status, migrationProgress.status) &&
        Objects.equals(this.totalMailboxes, migrationProgress.totalMailboxes) &&
        Objects.equals(this.completedMailboxes, migrationProgress.completedMailboxes) &&
        Objects.equals(this.failedMailboxes, migrationProgress.failedMailboxes) &&
        Objects.equals(this.totalMessages, migrationProgress.totalMessages) &&
        Objects.equals(this.syncedMessages, migrationProgress.syncedMessages) &&
        Objects.equals(this.failedMessages, migrationProgress.failedMessages) &&
        Objects.equals(this.percentComplete, migrationProgress.percentComplete) &&
        Objects.equals(this.mailboxes, migrationProgress.mailboxes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(migrationId, status, totalMailboxes, completedMailboxes, failedMailboxes, totalMessages, syncedMessages, failedMessages, percentComplete, mailboxes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MigrationProgress {\n");
    sb.append("    migrationId: ").append(toIndentedString(migrationId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    totalMailboxes: ").append(toIndentedString(totalMailboxes)).append("\n");
    sb.append("    completedMailboxes: ").append(toIndentedString(completedMailboxes)).append("\n");
    sb.append("    failedMailboxes: ").append(toIndentedString(failedMailboxes)).append("\n");
    sb.append("    totalMessages: ").append(toIndentedString(totalMessages)).append("\n");
    sb.append("    syncedMessages: ").append(toIndentedString(syncedMessages)).append("\n");
    sb.append("    failedMessages: ").append(toIndentedString(failedMessages)).append("\n");
    sb.append("    percentComplete: ").append(toIndentedString(percentComplete)).append("\n");
    sb.append("    mailboxes: ").append(toIndentedString(mailboxes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("migration_id", "status", "total_mailboxes", "completed_mailboxes", "failed_mailboxes", "total_messages", "synced_messages", "failed_messages", "percent_complete", "mailboxes"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("migration_id", "status", "total_mailboxes", "completed_mailboxes", "failed_mailboxes", "total_messages", "synced_messages", "failed_messages", "percent_complete", "mailboxes"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MigrationProgress
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MigrationProgress.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in MigrationProgress is not found in the empty JSON string", MigrationProgress.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MigrationProgress.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `MigrationProgress` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MigrationProgress.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("migration_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `migration_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("migration_id").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if (jsonObj.get("mailboxes") != null) {
        if (!jsonObj.get("mailboxes").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mailboxes` to be an array in the JSON string but got `%s`", jsonObj.get("mailboxes").toString()));
        }
        JsonArray jsonArraymailboxes = jsonObj.getAsJsonArray("mailboxes");
        // validate the required field `mailboxes` (array)
        for (int i = 0; i < jsonArraymailboxes.size(); i++) {
          MigrationProgressMailboxesInner.validateJsonElement(jsonArraymailboxes.get(i));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MigrationProgress.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MigrationProgress' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MigrationProgress> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MigrationProgress.class));

       return (TypeAdapter<T>) new TypeAdapter<MigrationProgress>() {
           @Override
           public void write(JsonWriter out, MigrationProgress value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MigrationProgress read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MigrationProgress given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MigrationProgress
   * @throws IOException if the JSON string is invalid with respect to MigrationProgress
   */
  public static MigrationProgress fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MigrationProgress.class);
  }

  /**
   * Convert an instance of MigrationProgress to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

