/*
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lockally.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.lockally.sdk.JSON;

/**
 * UnitBundle
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-02T21:47:01.311129+01:00[Africa/Lagos]", comments = "Generator version: 7.23.0")
public class UnitBundle {
  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  @jakarta.annotation.Nonnull
  private String key;

  public static final String SERIALIZED_NAME_UNITS = "units";
  @SerializedName(SERIALIZED_NAME_UNITS)
  @jakarta.annotation.Nonnull
  private Integer units;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "display_name";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  @jakarta.annotation.Nonnull
  private String displayName;

  public static final String SERIALIZED_NAME_PRICE_NAIRA = "price_naira";
  @SerializedName(SERIALIZED_NAME_PRICE_NAIRA)
  @jakarta.annotation.Nonnull
  private Integer priceNaira;

  public static final String SERIALIZED_NAME_DISPLAY_PRICE = "display_price";
  @SerializedName(SERIALIZED_NAME_DISPLAY_PRICE)
  @jakarta.annotation.Nonnull
  private String displayPrice;

  public UnitBundle() {
  }

  public UnitBundle key(@jakarta.annotation.Nonnull String key) {
    this.key = key;
    return this;
  }

  /**
   * Get key
   * @return key
   */
  @jakarta.annotation.Nonnull
  public String getKey() {
    return key;
  }

  public void setKey(@jakarta.annotation.Nonnull String key) {
    this.key = key;
  }


  public UnitBundle units(@jakarta.annotation.Nonnull Integer units) {
    this.units = units;
    return this;
  }

  /**
   * Get units
   * @return units
   */
  @jakarta.annotation.Nonnull
  public Integer getUnits() {
    return units;
  }

  public void setUnits(@jakarta.annotation.Nonnull Integer units) {
    this.units = units;
  }


  public UnitBundle displayName(@jakarta.annotation.Nonnull String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * Get displayName
   * @return displayName
   */
  @jakarta.annotation.Nonnull
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(@jakarta.annotation.Nonnull String displayName) {
    this.displayName = displayName;
  }


  public UnitBundle priceNaira(@jakarta.annotation.Nonnull Integer priceNaira) {
    this.priceNaira = priceNaira;
    return this;
  }

  /**
   * Get priceNaira
   * @return priceNaira
   */
  @jakarta.annotation.Nonnull
  public Integer getPriceNaira() {
    return priceNaira;
  }

  public void setPriceNaira(@jakarta.annotation.Nonnull Integer priceNaira) {
    this.priceNaira = priceNaira;
  }


  public UnitBundle displayPrice(@jakarta.annotation.Nonnull String displayPrice) {
    this.displayPrice = displayPrice;
    return this;
  }

  /**
   * Get displayPrice
   * @return displayPrice
   */
  @jakarta.annotation.Nonnull
  public String getDisplayPrice() {
    return displayPrice;
  }

  public void setDisplayPrice(@jakarta.annotation.Nonnull String displayPrice) {
    this.displayPrice = displayPrice;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnitBundle unitBundle = (UnitBundle) o;
    return Objects.equals(this.key, unitBundle.key) &&
        Objects.equals(this.units, unitBundle.units) &&
        Objects.equals(this.displayName, unitBundle.displayName) &&
        Objects.equals(this.priceNaira, unitBundle.priceNaira) &&
        Objects.equals(this.displayPrice, unitBundle.displayPrice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, units, displayName, priceNaira, displayPrice);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnitBundle {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    priceNaira: ").append(toIndentedString(priceNaira)).append("\n");
    sb.append("    displayPrice: ").append(toIndentedString(displayPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("key", "units", "display_name", "price_naira", "display_price"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("key", "units", "display_name", "price_naira", "display_price"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UnitBundle
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UnitBundle.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in UnitBundle is not found in the empty JSON string", UnitBundle.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UnitBundle.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `UnitBundle` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UnitBundle.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("key").toString()));
      }
      if (!jsonObj.get("display_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `display_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("display_name").toString()));
      }
      if (!jsonObj.get("display_price").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `display_price` to be a primitive type in the JSON string but got `%s`", jsonObj.get("display_price").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UnitBundle.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UnitBundle' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UnitBundle> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UnitBundle.class));

       return (TypeAdapter<T>) new TypeAdapter<UnitBundle>() {
           @Override
           public void write(JsonWriter out, UnitBundle value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UnitBundle read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UnitBundle given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UnitBundle
   * @throws IOException if the JSON string is invalid with respect to UnitBundle
   */
  public static UnitBundle fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UnitBundle.class);
  }

  /**
   * Convert an instance of UnitBundle to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

