/*
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lockally.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.lockally.sdk.JSON;

/**
 * UpdateCalendarPoliciesRequest
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-02T21:47:01.311129+01:00[Africa/Lagos]", comments = "Generator version: 7.23.0")
public class UpdateCalendarPoliciesRequest {
  public static final String SERIALIZED_NAME_MAX_MEETING_DURATION_MINS = "max_meeting_duration_mins";
  @SerializedName(SERIALIZED_NAME_MAX_MEETING_DURATION_MINS)
  @jakarta.annotation.Nullable
  private Integer maxMeetingDurationMins;

  public static final String SERIALIZED_NAME_WORKING_HOURS_START = "working_hours_start";
  @SerializedName(SERIALIZED_NAME_WORKING_HOURS_START)
  @jakarta.annotation.Nullable
  private String workingHoursStart;

  public static final String SERIALIZED_NAME_WORKING_HOURS_END = "working_hours_end";
  @SerializedName(SERIALIZED_NAME_WORKING_HOURS_END)
  @jakarta.annotation.Nullable
  private String workingHoursEnd;

  public static final String SERIALIZED_NAME_BOOKING_WINDOW_DAYS = "booking_window_days";
  @SerializedName(SERIALIZED_NAME_BOOKING_WINDOW_DAYS)
  @jakarta.annotation.Nullable
  private Integer bookingWindowDays;

  public static final String SERIALIZED_NAME_RECURRING_MEETING_LIMIT = "recurring_meeting_limit";
  @SerializedName(SERIALIZED_NAME_RECURRING_MEETING_LIMIT)
  @jakarta.annotation.Nullable
  private Integer recurringMeetingLimit;

  /**
   * Gets or Sets resourceApprovalMode
   */
  @JsonAdapter(ResourceApprovalModeEnum.Adapter.class)
  public enum ResourceApprovalModeEnum {
    AUTO_APPROVE("auto_approve"),
    
    REQUIRE_APPROVAL("require_approval"),
    
    RESTRICTED("restricted");

    private String value;

    ResourceApprovalModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ResourceApprovalModeEnum fromValue(String value) {
      for (ResourceApprovalModeEnum b : ResourceApprovalModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ResourceApprovalModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ResourceApprovalModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ResourceApprovalModeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ResourceApprovalModeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ResourceApprovalModeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_RESOURCE_APPROVAL_MODE = "resource_approval_mode";
  @SerializedName(SERIALIZED_NAME_RESOURCE_APPROVAL_MODE)
  @jakarta.annotation.Nullable
  private ResourceApprovalModeEnum resourceApprovalMode;

  public static final String SERIALIZED_NAME_EXTERNAL_INVITES_ALLOWED = "external_invites_allowed";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_INVITES_ALLOWED)
  @jakarta.annotation.Nullable
  private Boolean externalInvitesAllowed;

  public static final String SERIALIZED_NAME_EXTERNAL_SHARING_ALLOWED = "external_sharing_allowed";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_SHARING_ALLOWED)
  @jakarta.annotation.Nullable
  private Boolean externalSharingAllowed;

  public static final String SERIALIZED_NAME_PUBLIC_LINKS_ENABLED = "public_links_enabled";
  @SerializedName(SERIALIZED_NAME_PUBLIC_LINKS_ENABLED)
  @jakarta.annotation.Nullable
  private Boolean publicLinksEnabled;

  public UpdateCalendarPoliciesRequest() {
  }

  public UpdateCalendarPoliciesRequest maxMeetingDurationMins(@jakarta.annotation.Nullable Integer maxMeetingDurationMins) {
    this.maxMeetingDurationMins = maxMeetingDurationMins;
    return this;
  }

  /**
   * Get maxMeetingDurationMins
   * minimum: 15
   * maximum: 1440
   * @return maxMeetingDurationMins
   */
  @jakarta.annotation.Nullable
  public Integer getMaxMeetingDurationMins() {
    return maxMeetingDurationMins;
  }

  public void setMaxMeetingDurationMins(@jakarta.annotation.Nullable Integer maxMeetingDurationMins) {
    this.maxMeetingDurationMins = maxMeetingDurationMins;
  }


  public UpdateCalendarPoliciesRequest workingHoursStart(@jakarta.annotation.Nullable String workingHoursStart) {
    this.workingHoursStart = workingHoursStart;
    return this;
  }

  /**
   * Get workingHoursStart
   * @return workingHoursStart
   */
  @jakarta.annotation.Nullable
  public String getWorkingHoursStart() {
    return workingHoursStart;
  }

  public void setWorkingHoursStart(@jakarta.annotation.Nullable String workingHoursStart) {
    this.workingHoursStart = workingHoursStart;
  }


  public UpdateCalendarPoliciesRequest workingHoursEnd(@jakarta.annotation.Nullable String workingHoursEnd) {
    this.workingHoursEnd = workingHoursEnd;
    return this;
  }

  /**
   * Get workingHoursEnd
   * @return workingHoursEnd
   */
  @jakarta.annotation.Nullable
  public String getWorkingHoursEnd() {
    return workingHoursEnd;
  }

  public void setWorkingHoursEnd(@jakarta.annotation.Nullable String workingHoursEnd) {
    this.workingHoursEnd = workingHoursEnd;
  }


  public UpdateCalendarPoliciesRequest bookingWindowDays(@jakarta.annotation.Nullable Integer bookingWindowDays) {
    this.bookingWindowDays = bookingWindowDays;
    return this;
  }

  /**
   * Get bookingWindowDays
   * minimum: 1
   * maximum: 365
   * @return bookingWindowDays
   */
  @jakarta.annotation.Nullable
  public Integer getBookingWindowDays() {
    return bookingWindowDays;
  }

  public void setBookingWindowDays(@jakarta.annotation.Nullable Integer bookingWindowDays) {
    this.bookingWindowDays = bookingWindowDays;
  }


  public UpdateCalendarPoliciesRequest recurringMeetingLimit(@jakarta.annotation.Nullable Integer recurringMeetingLimit) {
    this.recurringMeetingLimit = recurringMeetingLimit;
    return this;
  }

  /**
   * Get recurringMeetingLimit
   * minimum: 1
   * maximum: 365
   * @return recurringMeetingLimit
   */
  @jakarta.annotation.Nullable
  public Integer getRecurringMeetingLimit() {
    return recurringMeetingLimit;
  }

  public void setRecurringMeetingLimit(@jakarta.annotation.Nullable Integer recurringMeetingLimit) {
    this.recurringMeetingLimit = recurringMeetingLimit;
  }


  public UpdateCalendarPoliciesRequest resourceApprovalMode(@jakarta.annotation.Nullable ResourceApprovalModeEnum resourceApprovalMode) {
    this.resourceApprovalMode = resourceApprovalMode;
    return this;
  }

  /**
   * Get resourceApprovalMode
   * @return resourceApprovalMode
   */
  @jakarta.annotation.Nullable
  public ResourceApprovalModeEnum getResourceApprovalMode() {
    return resourceApprovalMode;
  }

  public void setResourceApprovalMode(@jakarta.annotation.Nullable ResourceApprovalModeEnum resourceApprovalMode) {
    this.resourceApprovalMode = resourceApprovalMode;
  }


  public UpdateCalendarPoliciesRequest externalInvitesAllowed(@jakarta.annotation.Nullable Boolean externalInvitesAllowed) {
    this.externalInvitesAllowed = externalInvitesAllowed;
    return this;
  }

  /**
   * Get externalInvitesAllowed
   * @return externalInvitesAllowed
   */
  @jakarta.annotation.Nullable
  public Boolean getExternalInvitesAllowed() {
    return externalInvitesAllowed;
  }

  public void setExternalInvitesAllowed(@jakarta.annotation.Nullable Boolean externalInvitesAllowed) {
    this.externalInvitesAllowed = externalInvitesAllowed;
  }


  public UpdateCalendarPoliciesRequest externalSharingAllowed(@jakarta.annotation.Nullable Boolean externalSharingAllowed) {
    this.externalSharingAllowed = externalSharingAllowed;
    return this;
  }

  /**
   * Get externalSharingAllowed
   * @return externalSharingAllowed
   */
  @jakarta.annotation.Nullable
  public Boolean getExternalSharingAllowed() {
    return externalSharingAllowed;
  }

  public void setExternalSharingAllowed(@jakarta.annotation.Nullable Boolean externalSharingAllowed) {
    this.externalSharingAllowed = externalSharingAllowed;
  }


  public UpdateCalendarPoliciesRequest publicLinksEnabled(@jakarta.annotation.Nullable Boolean publicLinksEnabled) {
    this.publicLinksEnabled = publicLinksEnabled;
    return this;
  }

  /**
   * Get publicLinksEnabled
   * @return publicLinksEnabled
   */
  @jakarta.annotation.Nullable
  public Boolean getPublicLinksEnabled() {
    return publicLinksEnabled;
  }

  public void setPublicLinksEnabled(@jakarta.annotation.Nullable Boolean publicLinksEnabled) {
    this.publicLinksEnabled = publicLinksEnabled;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateCalendarPoliciesRequest updateCalendarPoliciesRequest = (UpdateCalendarPoliciesRequest) o;
    return Objects.equals(this.maxMeetingDurationMins, updateCalendarPoliciesRequest.maxMeetingDurationMins) &&
        Objects.equals(this.workingHoursStart, updateCalendarPoliciesRequest.workingHoursStart) &&
        Objects.equals(this.workingHoursEnd, updateCalendarPoliciesRequest.workingHoursEnd) &&
        Objects.equals(this.bookingWindowDays, updateCalendarPoliciesRequest.bookingWindowDays) &&
        Objects.equals(this.recurringMeetingLimit, updateCalendarPoliciesRequest.recurringMeetingLimit) &&
        Objects.equals(this.resourceApprovalMode, updateCalendarPoliciesRequest.resourceApprovalMode) &&
        Objects.equals(this.externalInvitesAllowed, updateCalendarPoliciesRequest.externalInvitesAllowed) &&
        Objects.equals(this.externalSharingAllowed, updateCalendarPoliciesRequest.externalSharingAllowed) &&
        Objects.equals(this.publicLinksEnabled, updateCalendarPoliciesRequest.publicLinksEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxMeetingDurationMins, workingHoursStart, workingHoursEnd, bookingWindowDays, recurringMeetingLimit, resourceApprovalMode, externalInvitesAllowed, externalSharingAllowed, publicLinksEnabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateCalendarPoliciesRequest {\n");
    sb.append("    maxMeetingDurationMins: ").append(toIndentedString(maxMeetingDurationMins)).append("\n");
    sb.append("    workingHoursStart: ").append(toIndentedString(workingHoursStart)).append("\n");
    sb.append("    workingHoursEnd: ").append(toIndentedString(workingHoursEnd)).append("\n");
    sb.append("    bookingWindowDays: ").append(toIndentedString(bookingWindowDays)).append("\n");
    sb.append("    recurringMeetingLimit: ").append(toIndentedString(recurringMeetingLimit)).append("\n");
    sb.append("    resourceApprovalMode: ").append(toIndentedString(resourceApprovalMode)).append("\n");
    sb.append("    externalInvitesAllowed: ").append(toIndentedString(externalInvitesAllowed)).append("\n");
    sb.append("    externalSharingAllowed: ").append(toIndentedString(externalSharingAllowed)).append("\n");
    sb.append("    publicLinksEnabled: ").append(toIndentedString(publicLinksEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("max_meeting_duration_mins", "working_hours_start", "working_hours_end", "booking_window_days", "recurring_meeting_limit", "resource_approval_mode", "external_invites_allowed", "external_sharing_allowed", "public_links_enabled"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateCalendarPoliciesRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateCalendarPoliciesRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in UpdateCalendarPoliciesRequest is not found in the empty JSON string", UpdateCalendarPoliciesRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateCalendarPoliciesRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `UpdateCalendarPoliciesRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("working_hours_start") != null && !jsonObj.get("working_hours_start").isJsonNull()) && !jsonObj.get("working_hours_start").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `working_hours_start` to be a primitive type in the JSON string but got `%s`", jsonObj.get("working_hours_start").toString()));
      }
      if ((jsonObj.get("working_hours_end") != null && !jsonObj.get("working_hours_end").isJsonNull()) && !jsonObj.get("working_hours_end").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `working_hours_end` to be a primitive type in the JSON string but got `%s`", jsonObj.get("working_hours_end").toString()));
      }
      if ((jsonObj.get("resource_approval_mode") != null && !jsonObj.get("resource_approval_mode").isJsonNull()) && !jsonObj.get("resource_approval_mode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `resource_approval_mode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("resource_approval_mode").toString()));
      }
      // validate the optional field `resource_approval_mode`
      if (jsonObj.get("resource_approval_mode") != null && !jsonObj.get("resource_approval_mode").isJsonNull()) {
        ResourceApprovalModeEnum.validateJsonElement(jsonObj.get("resource_approval_mode"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateCalendarPoliciesRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateCalendarPoliciesRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateCalendarPoliciesRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateCalendarPoliciesRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateCalendarPoliciesRequest>() {
           @Override
           public void write(JsonWriter out, UpdateCalendarPoliciesRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateCalendarPoliciesRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateCalendarPoliciesRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateCalendarPoliciesRequest
   * @throws IOException if the JSON string is invalid with respect to UpdateCalendarPoliciesRequest
   */
  public static UpdateCalendarPoliciesRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateCalendarPoliciesRequest.class);
  }

  /**
   * Convert an instance of UpdateCalendarPoliciesRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

