/*
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lockally.sdk.api;

import com.lockally.sdk.ApiCallback;
import com.lockally.sdk.ApiClient;
import com.lockally.sdk.ApiException;
import com.lockally.sdk.ApiResponse;
import com.lockally.sdk.Configuration;
import com.lockally.sdk.Pair;
import com.lockally.sdk.ProgressRequestBody;
import com.lockally.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.lockally.sdk.model.AddContactListMemberRequest;
import com.lockally.sdk.model.ContactList;
import com.lockally.sdk.model.CreateContactListRequest;
import com.lockally.sdk.model.GetContactList200Response;
import com.lockally.sdk.model.ListContactLists200Response;
import com.lockally.sdk.model.Problem;
import java.util.UUID;
import com.lockally.sdk.model.UpdateContactListRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ContactListsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ContactListsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ContactListsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for addContactListMember
     * @param id  (required)
     * @param addContactListMemberRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Member added </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addContactListMemberCall(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull AddContactListMemberRequest addContactListMemberRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = addContactListMemberRequest;

        // create path and map variables
        String localVarPath = "/v1/contact-lists/{id}/members"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call addContactListMemberValidateBeforeCall(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull AddContactListMemberRequest addContactListMemberRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling addContactListMember(Async)");
        }

        // verify the required parameter 'addContactListMemberRequest' is set
        if (addContactListMemberRequest == null) {
            throw new ApiException("Missing the required parameter 'addContactListMemberRequest' when calling addContactListMember(Async)");
        }

        return addContactListMemberCall(id, addContactListMemberRequest, _callback);

    }

    /**
     * Add a member to a contact list
     * 
     * @param id  (required)
     * @param addContactListMemberRequest  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Member added </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public void addContactListMember(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull AddContactListMemberRequest addContactListMemberRequest) throws ApiException {
        addContactListMemberWithHttpInfo(id, addContactListMemberRequest);
    }

    /**
     * Add a member to a contact list
     * 
     * @param id  (required)
     * @param addContactListMemberRequest  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Member added </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> addContactListMemberWithHttpInfo(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull AddContactListMemberRequest addContactListMemberRequest) throws ApiException {
        okhttp3.Call localVarCall = addContactListMemberValidateBeforeCall(id, addContactListMemberRequest, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Add a member to a contact list (asynchronously)
     * 
     * @param id  (required)
     * @param addContactListMemberRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Member added </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addContactListMemberAsync(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull AddContactListMemberRequest addContactListMemberRequest, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = addContactListMemberValidateBeforeCall(id, addContactListMemberRequest, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for createContactList
     * @param createContactListRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Contact list created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createContactListCall(@jakarta.annotation.Nonnull CreateContactListRequest createContactListRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createContactListRequest;

        // create path and map variables
        String localVarPath = "/v1/contact-lists";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json",
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createContactListValidateBeforeCall(@jakarta.annotation.Nonnull CreateContactListRequest createContactListRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createContactListRequest' is set
        if (createContactListRequest == null) {
            throw new ApiException("Missing the required parameter 'createContactListRequest' when calling createContactList(Async)");
        }

        return createContactListCall(createContactListRequest, _callback);

    }

    /**
     * Create a contact list
     * 
     * @param createContactListRequest  (required)
     * @return ContactList
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Contact list created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
     </table>
     */
    public ContactList createContactList(@jakarta.annotation.Nonnull CreateContactListRequest createContactListRequest) throws ApiException {
        ApiResponse<ContactList> localVarResp = createContactListWithHttpInfo(createContactListRequest);
        return localVarResp.getData();
    }

    /**
     * Create a contact list
     * 
     * @param createContactListRequest  (required)
     * @return ApiResponse&lt;ContactList&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Contact list created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ContactList> createContactListWithHttpInfo(@jakarta.annotation.Nonnull CreateContactListRequest createContactListRequest) throws ApiException {
        okhttp3.Call localVarCall = createContactListValidateBeforeCall(createContactListRequest, null);
        Type localVarReturnType = new TypeToken<ContactList>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a contact list (asynchronously)
     * 
     * @param createContactListRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Contact list created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createContactListAsync(@jakarta.annotation.Nonnull CreateContactListRequest createContactListRequest, final ApiCallback<ContactList> _callback) throws ApiException {

        okhttp3.Call localVarCall = createContactListValidateBeforeCall(createContactListRequest, _callback);
        Type localVarReturnType = new TypeToken<ContactList>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteContactList
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Contact list deleted </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteContactListCall(@jakarta.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/contact-lists/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteContactListValidateBeforeCall(@jakarta.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deleteContactList(Async)");
        }

        return deleteContactListCall(id, _callback);

    }

    /**
     * Delete a contact list
     * 
     * @param id  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Contact list deleted </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public void deleteContactList(@jakarta.annotation.Nonnull UUID id) throws ApiException {
        deleteContactListWithHttpInfo(id);
    }

    /**
     * Delete a contact list
     * 
     * @param id  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Contact list deleted </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deleteContactListWithHttpInfo(@jakarta.annotation.Nonnull UUID id) throws ApiException {
        okhttp3.Call localVarCall = deleteContactListValidateBeforeCall(id, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Delete a contact list (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Contact list deleted </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteContactListAsync(@jakarta.annotation.Nonnull UUID id, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteContactListValidateBeforeCall(id, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for getContactList
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Contact list with members </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getContactListCall(@jakarta.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/contact-lists/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json",
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getContactListValidateBeforeCall(@jakarta.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getContactList(Async)");
        }

        return getContactListCall(id, _callback);

    }

    /**
     * Get a contact list with members
     * 
     * @param id  (required)
     * @return GetContactList200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Contact list with members </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public GetContactList200Response getContactList(@jakarta.annotation.Nonnull UUID id) throws ApiException {
        ApiResponse<GetContactList200Response> localVarResp = getContactListWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get a contact list with members
     * 
     * @param id  (required)
     * @return ApiResponse&lt;GetContactList200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Contact list with members </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetContactList200Response> getContactListWithHttpInfo(@jakarta.annotation.Nonnull UUID id) throws ApiException {
        okhttp3.Call localVarCall = getContactListValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<GetContactList200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get a contact list with members (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Contact list with members </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getContactListAsync(@jakarta.annotation.Nonnull UUID id, final ApiCallback<GetContactList200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getContactListValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<GetContactList200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listContactLists
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of contact lists </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listContactListsCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/contact-lists";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json",
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listContactListsValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return listContactListsCall(_callback);

    }

    /**
     * List contact lists
     * 
     * @return ListContactLists200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of contact lists </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
     </table>
     */
    public ListContactLists200Response listContactLists() throws ApiException {
        ApiResponse<ListContactLists200Response> localVarResp = listContactListsWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * List contact lists
     * 
     * @return ApiResponse&lt;ListContactLists200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of contact lists </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ListContactLists200Response> listContactListsWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = listContactListsValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<ListContactLists200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List contact lists (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of contact lists </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listContactListsAsync(final ApiCallback<ListContactLists200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = listContactListsValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<ListContactLists200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for removeContactListMember
     * @param id  (required)
     * @param contactId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Member removed </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call removeContactListMemberCall(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull UUID contactId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/contact-lists/{id}/members/{contactId}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()))
            .replace("{" + "contactId" + "}", localVarApiClient.escapeString(contactId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call removeContactListMemberValidateBeforeCall(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull UUID contactId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling removeContactListMember(Async)");
        }

        // verify the required parameter 'contactId' is set
        if (contactId == null) {
            throw new ApiException("Missing the required parameter 'contactId' when calling removeContactListMember(Async)");
        }

        return removeContactListMemberCall(id, contactId, _callback);

    }

    /**
     * Remove a member from a contact list
     * 
     * @param id  (required)
     * @param contactId  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Member removed </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public void removeContactListMember(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull UUID contactId) throws ApiException {
        removeContactListMemberWithHttpInfo(id, contactId);
    }

    /**
     * Remove a member from a contact list
     * 
     * @param id  (required)
     * @param contactId  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Member removed </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> removeContactListMemberWithHttpInfo(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull UUID contactId) throws ApiException {
        okhttp3.Call localVarCall = removeContactListMemberValidateBeforeCall(id, contactId, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Remove a member from a contact list (asynchronously)
     * 
     * @param id  (required)
     * @param contactId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Member removed </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call removeContactListMemberAsync(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull UUID contactId, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = removeContactListMemberValidateBeforeCall(id, contactId, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateContactList
     * @param id  (required)
     * @param updateContactListRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Contact list updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateContactListCall(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull UpdateContactListRequest updateContactListRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateContactListRequest;

        // create path and map variables
        String localVarPath = "/v1/contact-lists/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json",
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateContactListValidateBeforeCall(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull UpdateContactListRequest updateContactListRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling updateContactList(Async)");
        }

        // verify the required parameter 'updateContactListRequest' is set
        if (updateContactListRequest == null) {
            throw new ApiException("Missing the required parameter 'updateContactListRequest' when calling updateContactList(Async)");
        }

        return updateContactListCall(id, updateContactListRequest, _callback);

    }

    /**
     * Update a contact list
     * 
     * @param id  (required)
     * @param updateContactListRequest  (required)
     * @return ContactList
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Contact list updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public ContactList updateContactList(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull UpdateContactListRequest updateContactListRequest) throws ApiException {
        ApiResponse<ContactList> localVarResp = updateContactListWithHttpInfo(id, updateContactListRequest);
        return localVarResp.getData();
    }

    /**
     * Update a contact list
     * 
     * @param id  (required)
     * @param updateContactListRequest  (required)
     * @return ApiResponse&lt;ContactList&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Contact list updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ContactList> updateContactListWithHttpInfo(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull UpdateContactListRequest updateContactListRequest) throws ApiException {
        okhttp3.Call localVarCall = updateContactListValidateBeforeCall(id, updateContactListRequest, null);
        Type localVarReturnType = new TypeToken<ContactList>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update a contact list (asynchronously)
     * 
     * @param id  (required)
     * @param updateContactListRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Contact list updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateContactListAsync(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull UpdateContactListRequest updateContactListRequest, final ApiCallback<ContactList> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateContactListValidateBeforeCall(id, updateContactListRequest, _callback);
        Type localVarReturnType = new TypeToken<ContactList>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
