/*
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lockally.sdk.api;

import com.lockally.sdk.ApiCallback;
import com.lockally.sdk.ApiClient;
import com.lockally.sdk.ApiException;
import com.lockally.sdk.ApiResponse;
import com.lockally.sdk.Configuration;
import com.lockally.sdk.Pair;
import com.lockally.sdk.ProgressRequestBody;
import com.lockally.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.lockally.sdk.model.CreateResourceRequest;
import com.lockally.sdk.model.ListResources200Response;
import com.lockally.sdk.model.Problem;
import com.lockally.sdk.model.Resource;
import java.util.UUID;
import com.lockally.sdk.model.UpdateResourceRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ResourcesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ResourcesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ResourcesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createResource
     * @param createResourceRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Resource created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createResourceCall(@jakarta.annotation.Nonnull CreateResourceRequest createResourceRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createResourceRequest;

        // create path and map variables
        String localVarPath = "/v1/resources";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json",
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createResourceValidateBeforeCall(@jakarta.annotation.Nonnull CreateResourceRequest createResourceRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createResourceRequest' is set
        if (createResourceRequest == null) {
            throw new ApiException("Missing the required parameter 'createResourceRequest' when calling createResource(Async)");
        }

        return createResourceCall(createResourceRequest, _callback);

    }

    /**
     * Create a resource
     * 
     * @param createResourceRequest  (required)
     * @return Resource
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Resource created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
     </table>
     */
    public Resource createResource(@jakarta.annotation.Nonnull CreateResourceRequest createResourceRequest) throws ApiException {
        ApiResponse<Resource> localVarResp = createResourceWithHttpInfo(createResourceRequest);
        return localVarResp.getData();
    }

    /**
     * Create a resource
     * 
     * @param createResourceRequest  (required)
     * @return ApiResponse&lt;Resource&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Resource created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Resource> createResourceWithHttpInfo(@jakarta.annotation.Nonnull CreateResourceRequest createResourceRequest) throws ApiException {
        okhttp3.Call localVarCall = createResourceValidateBeforeCall(createResourceRequest, null);
        Type localVarReturnType = new TypeToken<Resource>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a resource (asynchronously)
     * 
     * @param createResourceRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Resource created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createResourceAsync(@jakarta.annotation.Nonnull CreateResourceRequest createResourceRequest, final ApiCallback<Resource> _callback) throws ApiException {

        okhttp3.Call localVarCall = createResourceValidateBeforeCall(createResourceRequest, _callback);
        Type localVarReturnType = new TypeToken<Resource>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteResource
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> No content </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteResourceCall(@jakarta.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/resources/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteResourceValidateBeforeCall(@jakarta.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deleteResource(Async)");
        }

        return deleteResourceCall(id, _callback);

    }

    /**
     * Delete a resource
     * 
     * @param id  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> No content </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public void deleteResource(@jakarta.annotation.Nonnull UUID id) throws ApiException {
        deleteResourceWithHttpInfo(id);
    }

    /**
     * Delete a resource
     * 
     * @param id  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> No content </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deleteResourceWithHttpInfo(@jakarta.annotation.Nonnull UUID id) throws ApiException {
        okhttp3.Call localVarCall = deleteResourceValidateBeforeCall(id, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Delete a resource (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> No content </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteResourceAsync(@jakarta.annotation.Nonnull UUID id, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteResourceValidateBeforeCall(id, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for getResource
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Resource details </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getResourceCall(@jakarta.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/resources/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json",
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getResourceValidateBeforeCall(@jakarta.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getResource(Async)");
        }

        return getResourceCall(id, _callback);

    }

    /**
     * Get a resource
     * 
     * @param id  (required)
     * @return Resource
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Resource details </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public Resource getResource(@jakarta.annotation.Nonnull UUID id) throws ApiException {
        ApiResponse<Resource> localVarResp = getResourceWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get a resource
     * 
     * @param id  (required)
     * @return ApiResponse&lt;Resource&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Resource details </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Resource> getResourceWithHttpInfo(@jakarta.annotation.Nonnull UUID id) throws ApiException {
        okhttp3.Call localVarCall = getResourceValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Resource>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get a resource (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Resource details </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getResourceAsync(@jakarta.annotation.Nonnull UUID id, final ApiCallback<Resource> _callback) throws ApiException {

        okhttp3.Call localVarCall = getResourceValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Resource>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listResources
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of resources </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listResourcesCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/resources";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json",
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listResourcesValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return listResourcesCall(_callback);

    }

    /**
     * List resources
     * 
     * @return ListResources200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of resources </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
     </table>
     */
    public ListResources200Response listResources() throws ApiException {
        ApiResponse<ListResources200Response> localVarResp = listResourcesWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * List resources
     * 
     * @return ApiResponse&lt;ListResources200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of resources </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ListResources200Response> listResourcesWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = listResourcesValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<ListResources200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List resources (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of resources </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listResourcesAsync(final ApiCallback<ListResources200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = listResourcesValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<ListResources200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateResource
     * @param id  (required)
     * @param updateResourceRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Resource updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateResourceCall(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull UpdateResourceRequest updateResourceRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateResourceRequest;

        // create path and map variables
        String localVarPath = "/v1/resources/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json",
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateResourceValidateBeforeCall(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull UpdateResourceRequest updateResourceRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling updateResource(Async)");
        }

        // verify the required parameter 'updateResourceRequest' is set
        if (updateResourceRequest == null) {
            throw new ApiException("Missing the required parameter 'updateResourceRequest' when calling updateResource(Async)");
        }

        return updateResourceCall(id, updateResourceRequest, _callback);

    }

    /**
     * Update a resource
     * 
     * @param id  (required)
     * @param updateResourceRequest  (required)
     * @return Resource
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Resource updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public Resource updateResource(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull UpdateResourceRequest updateResourceRequest) throws ApiException {
        ApiResponse<Resource> localVarResp = updateResourceWithHttpInfo(id, updateResourceRequest);
        return localVarResp.getData();
    }

    /**
     * Update a resource
     * 
     * @param id  (required)
     * @param updateResourceRequest  (required)
     * @return ApiResponse&lt;Resource&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Resource updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Resource> updateResourceWithHttpInfo(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull UpdateResourceRequest updateResourceRequest) throws ApiException {
        okhttp3.Call localVarCall = updateResourceValidateBeforeCall(id, updateResourceRequest, null);
        Type localVarReturnType = new TypeToken<Resource>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update a resource (asynchronously)
     * 
     * @param id  (required)
     * @param updateResourceRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Resource updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Malformed request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, malformed, or invalid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API key lacks the required scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found under the calling tenant. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateResourceAsync(@jakarta.annotation.Nonnull UUID id, @jakarta.annotation.Nonnull UpdateResourceRequest updateResourceRequest, final ApiCallback<Resource> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateResourceValidateBeforeCall(id, updateResourceRequest, _callback);
        Type localVarReturnType = new TypeToken<Resource>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
