/*
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lockally.sdk.api;

import com.lockally.sdk.ApiException;
import com.lockally.sdk.model.AdminFull;
import com.lockally.sdk.model.Problem;
import java.util.UUID;
import com.lockally.sdk.model.V1AdminsGet200Response;
import com.lockally.sdk.model.V1AdminsIdPatchRequest;
import com.lockally.sdk.model.V1AdminsPostRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdminsApi
 */
@Disabled
public class AdminsApiTest {

    private final AdminsApi api = new AdminsApi();

    /**
     * List tenant admins
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AdminsGetTest() throws ApiException {
        V1AdminsGet200Response response = api.v1AdminsGet();
        // TODO: test validations
    }

    /**
     * Delete an admin
     *
     * Hard-delete. Cascade-drops the admin&#39;s sessions (immediate revocation). Same safety rails as PATCH disabled&#x3D;true. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AdminsIdDeleteTest() throws ApiException {
        UUID id = null;
        api.v1AdminsIdDelete(id);
        // TODO: test validations
    }

    /**
     * Update an admin
     *
     * Supply at least one of &#x60;password&#x60;, &#x60;display_name&#x60;, &#x60;role&#x60;, &#x60;disabled&#x60;.  **Safety rails.** A session bearer (adm_sess_*) cannot disable itself — use another admin or an API key (which bypasses the self-rail). Disabling the last active admin returns 409 to prevent orphaning the tenant from its console. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AdminsIdPatchTest() throws ApiException {
        UUID id = null;
        V1AdminsIdPatchRequest v1AdminsIdPatchRequest = null;
        AdminFull response = api.v1AdminsIdPatch(id, v1AdminsIdPatchRequest);
        // TODO: test validations
    }

    /**
     * Invite a new admin
     *
     * Creates a new tenant admin. If &#x60;password&#x60; is omitted, lockally generates a 16-char password and returns it ONCE in the response. Email is case-insensitive and unique per tenant. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AdminsPostTest() throws ApiException {
        V1AdminsPostRequest v1AdminsPostRequest = null;
        AdminFull response = api.v1AdminsPost(v1AdminsPostRequest);
        // TODO: test validations
    }

}
