/*
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lockally.sdk.api;

import com.lockally.sdk.ApiException;
import com.lockally.sdk.model.AddContactListMemberRequest;
import com.lockally.sdk.model.ContactList;
import com.lockally.sdk.model.CreateContactListRequest;
import com.lockally.sdk.model.GetContactList200Response;
import com.lockally.sdk.model.ListContactLists200Response;
import com.lockally.sdk.model.Problem;
import java.util.UUID;
import com.lockally.sdk.model.UpdateContactListRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContactListsApi
 */
@Disabled
public class ContactListsApiTest {

    private final ContactListsApi api = new ContactListsApi();

    /**
     * Add a member to a contact list
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addContactListMemberTest() throws ApiException {
        UUID id = null;
        AddContactListMemberRequest addContactListMemberRequest = null;
        api.addContactListMember(id, addContactListMemberRequest);
        // TODO: test validations
    }

    /**
     * Create a contact list
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createContactListTest() throws ApiException {
        CreateContactListRequest createContactListRequest = null;
        ContactList response = api.createContactList(createContactListRequest);
        // TODO: test validations
    }

    /**
     * Delete a contact list
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteContactListTest() throws ApiException {
        UUID id = null;
        api.deleteContactList(id);
        // TODO: test validations
    }

    /**
     * Get a contact list with members
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getContactListTest() throws ApiException {
        UUID id = null;
        GetContactList200Response response = api.getContactList(id);
        // TODO: test validations
    }

    /**
     * List contact lists
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listContactListsTest() throws ApiException {
        ListContactLists200Response response = api.listContactLists();
        // TODO: test validations
    }

    /**
     * Remove a member from a contact list
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeContactListMemberTest() throws ApiException {
        UUID id = null;
        UUID contactId = null;
        api.removeContactListMember(id, contactId);
        // TODO: test validations
    }

    /**
     * Update a contact list
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateContactListTest() throws ApiException {
        UUID id = null;
        UpdateContactListRequest updateContactListRequest = null;
        ContactList response = api.updateContactList(id, updateContactListRequest);
        // TODO: test validations
    }

}
