/*
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lockally.sdk.api;

import com.lockally.sdk.ApiException;
import com.lockally.sdk.model.DirectoryPermissions;
import com.lockally.sdk.model.GALSettings;
import com.lockally.sdk.model.GetDirectoryActivity200Response;
import com.lockally.sdk.model.GetDirectoryStats200Response;
import com.lockally.sdk.model.Problem;
import com.lockally.sdk.model.UpdateDirectoryPermissionsRequest;
import com.lockally.sdk.model.UpdateGALSettingsRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DirectoryApi
 */
@Disabled
public class DirectoryApiTest {

    private final DirectoryApi api = new DirectoryApi();

    /**
     * Get recent directory activity
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDirectoryActivityTest() throws ApiException {
        GetDirectoryActivity200Response response = api.getDirectoryActivity();
        // TODO: test validations
    }

    /**
     * Get directory permission settings
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDirectoryPermissionsTest() throws ApiException {
        DirectoryPermissions response = api.getDirectoryPermissions();
        // TODO: test validations
    }

    /**
     * Get directory statistics
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDirectoryStatsTest() throws ApiException {
        GetDirectoryStats200Response response = api.getDirectoryStats();
        // TODO: test validations
    }

    /**
     * Get Global Address List settings
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getGALSettingsTest() throws ApiException {
        GALSettings response = api.getGALSettings();
        // TODO: test validations
    }

    /**
     * Rebuild the GAL search index
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void rebuildGALIndexTest() throws ApiException {
        GALSettings response = api.rebuildGALIndex();
        // TODO: test validations
    }

    /**
     * Sync GAL with external directory sources
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void syncGALTest() throws ApiException {
        GALSettings response = api.syncGAL();
        // TODO: test validations
    }

    /**
     * Update directory permission settings
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateDirectoryPermissionsTest() throws ApiException {
        UpdateDirectoryPermissionsRequest updateDirectoryPermissionsRequest = null;
        DirectoryPermissions response = api.updateDirectoryPermissions(updateDirectoryPermissionsRequest);
        // TODO: test validations
    }

    /**
     * Update GAL settings
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateGALSettingsTest() throws ApiException {
        UpdateGALSettingsRequest updateGALSettingsRequest = null;
        GALSettings response = api.updateGALSettings(updateGALSettingsRequest);
        // TODO: test validations
    }

}
