/*
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lockally.sdk.api;

import com.lockally.sdk.ApiException;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DraftsApi
 */
@Disabled
public class DraftsApiTest {

    private final DraftsApi api = new DraftsApi();

    /**
     * Approve a pending draft (human)
     *
     * Sends the draft exactly as reviewed, through the agent stream (loop detector included). Fires draft.approved.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1DraftsDraftIDApprovePostTest() throws ApiException {
        UUID draftID = null;
        Object response = api.v1DraftsDraftIDApprovePost(draftID);
        // TODO: test validations
    }

    /**
     * Withdraw a pending draft
     *
     * Only the API key that created the draft may cancel it.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1DraftsDraftIDCancelPostTest() throws ApiException {
        UUID draftID = null;
        Object response = api.v1DraftsDraftIDCancelPost(draftID);
        // TODO: test validations
    }

    /**
     * Get a draft
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1DraftsDraftIDGetTest() throws ApiException {
        UUID draftID = null;
        Object response = api.v1DraftsDraftIDGet(draftID);
        // TODO: test validations
    }

    /**
     * Reject a pending draft (human)
     *
     * Body: {\&quot;reason\&quot;: \&quot;...\&quot;} (optional). Fires draft.rejected.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1DraftsDraftIDRejectPostTest() throws ApiException {
        UUID draftID = null;
        Object response = api.v1DraftsDraftIDRejectPost(draftID);
        // TODO: test validations
    }

    /**
     * List drafts
     *
     * Filter with ?status&#x3D;pending_approval|sent|rejected|cancelled. Keys see drafts of granted mailboxes; admin sessions see all.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1DraftsGetTest() throws ApiException {
        String status = null;
        Integer limit = null;
        Object response = api.v1DraftsGet(status, limit);
        // TODO: test validations
    }

    /**
     * Propose a new conversation as a draft
     *
     * New-conversation drafts ALWAYS require human approval (policy flag new_thread). Idempotency-Key required.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1InboxesMailboxDraftsPostTest() throws ApiException {
        String mailbox = null;
        String idempotencyKey = null;
        Object response = api.v1InboxesMailboxDraftsPost(mailbox, idempotencyKey);
        // TODO: test validations
    }

    /**
     * Propose a reply as a draft
     *
     * The safe default over /reply: the deterministic policy engine auto-sends clean in-thread replies and holds anything risky (PII, new recipients, injection-flagged threads, always-approve mailboxes) for human approval. Fires draft.pending_approval when held. Idempotency-Key required.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1ThreadsThreadIDDraftsPostTest() throws ApiException {
        UUID threadID = null;
        String idempotencyKey = null;
        Object response = api.v1ThreadsThreadIDDraftsPost(threadID, idempotencyKey);
        // TODO: test validations
    }

}
