/*
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lockally.sdk.api;

import com.lockally.sdk.ApiException;
import com.lockally.sdk.model.AddSharedMemberRequest;
import java.io.File;
import com.lockally.sdk.model.ListSharedMembers200Response;
import com.lockally.sdk.model.Mailbox;
import com.lockally.sdk.model.Problem;
import com.lockally.sdk.model.SharedMember;
import com.lockally.sdk.model.V1MailboxesEmailExportPost201Response;
import com.lockally.sdk.model.V1MailboxesEmailPatchRequest;
import com.lockally.sdk.model.V1MailboxesEmailVacationPutRequest;
import com.lockally.sdk.model.V1MailboxesGet200Response;
import com.lockally.sdk.model.V1MailboxesPostRequest;
import com.lockally.sdk.model.V1VacationGet200Response;
import com.lockally.sdk.model.VacationResponder;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MailboxesApi
 */
@Disabled
public class MailboxesApiTest {

    private final MailboxesApi api = new MailboxesApi();

    /**
     * Add a shared mailbox member
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addSharedMemberTest() throws ApiException {
        String email = null;
        AddSharedMemberRequest addSharedMemberRequest = null;
        SharedMember response = api.addSharedMember(email, addSharedMemberRequest);
        // TODO: test validations
    }

    /**
     * List shared mailbox members
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listSharedMembersTest() throws ApiException {
        String email = null;
        ListSharedMembers200Response response = api.listSharedMembers(email);
        // TODO: test validations
    }

    /**
     * Remove a shared mailbox member
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeSharedMemberTest() throws ApiException {
        String email = null;
        String memberEmail = null;
        api.removeSharedMember(email, memberEmail);
        // TODO: test validations
    }

    /**
     * Soft-delete a mailbox
     *
     * Sets &#x60;soft_deleted_at &#x3D; now()&#x60; and &#x60;hard_delete_after &#x3D; now() + 90d&#x60; per design D25. A background sweep (planned) will hard-delete after the window. The mailbox is also disabled immediately. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1MailboxesEmailDeleteTest() throws ApiException {
        String email = null;
        api.v1MailboxesEmailDelete(email);
        // TODO: test validations
    }

    /**
     * Download a previously-issued mailbox export
     *
     * Public endpoint (no Authorization header). Validates the one-shot token from the URL, marks it used, and streams an mbox file. Second GET with the same token returns 404 — tokens are single-use. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1MailboxesEmailExportDownloadGetTest() throws ApiException {
        String email = null;
        String token = null;
        File response = api.v1MailboxesEmailExportDownloadGet(email, token);
        // TODO: test validations
    }

    /**
     * Request a mailbox export
     *
     * Issues a one-shot \&quot;presigned\&quot; download URL for the mailbox&#39;s content in mbox format. The URL works without an Authorization header — the token in the query string is the authz. TTL is 5 minutes; the token is consumed on first GET.  **v1 caveat:** the synthesized mbox only contains outbound mail (from &#x60;lockally.messages&#x60;). v2 swaps in Stalwart&#39;s export primitive for full inbox + folder structure + flags. The endpoint contract stays unchanged. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1MailboxesEmailExportPostTest() throws ApiException {
        String email = null;
        V1MailboxesEmailExportPost201Response response = api.v1MailboxesEmailExportPost(email);
        // TODO: test validations
    }

    /**
     * Get a mailbox
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1MailboxesEmailGetTest() throws ApiException {
        String email = null;
        Mailbox response = api.v1MailboxesEmailGet(email);
        // TODO: test validations
    }

    /**
     * Update a mailbox
     *
     * Supply at least one of &#x60;password&#x60;, &#x60;quota_bytes&#x60;, &#x60;disabled&#x60;. Returns the updated mailbox. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1MailboxesEmailPatchTest() throws ApiException {
        String email = null;
        V1MailboxesEmailPatchRequest v1MailboxesEmailPatchRequest = null;
        Mailbox response = api.v1MailboxesEmailPatch(email, v1MailboxesEmailPatchRequest);
        // TODO: test validations
    }

    /**
     * Remove the vacation responder
     *
     * Idempotent — 204 whether or not a row existed.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1MailboxesEmailVacationDeleteTest() throws ApiException {
        String email = null;
        api.v1MailboxesEmailVacationDelete(email);
        // TODO: test validations
    }

    /**
     * Get the vacation responder
     *
     * Returns the stored vacation rule or 404 if none is set.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1MailboxesEmailVacationGetTest() throws ApiException {
        String email = null;
        VacationResponder response = api.v1MailboxesEmailVacationGet(email);
        // TODO: test validations
    }

    /**
     * Set the vacation responder
     *
     * Upsert — same endpoint creates or replaces the rule. Clears &#x60;synced_at&#x60;; the rule is staged on lockally until a sync worker pushes it to the mail server. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1MailboxesEmailVacationPutTest() throws ApiException {
        String email = null;
        V1MailboxesEmailVacationPutRequest v1MailboxesEmailVacationPutRequest = null;
        VacationResponder response = api.v1MailboxesEmailVacationPut(email, v1MailboxesEmailVacationPutRequest);
        // TODO: test validations
    }

    /**
     * List mailboxes
     *
     * Returns mailboxes under the calling tenant — active and soft-deleted. &#x60;?limit&#x3D;N&#x60; between 1 and 200 (default 50). 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1MailboxesGetTest() throws ApiException {
        Integer limit = null;
        V1MailboxesGet200Response response = api.v1MailboxesGet(limit);
        // TODO: test validations
    }

    /**
     * Create a mailbox
     *
     * Creates a mailbox on a tenant-verified domain. If &#x60;password&#x60; is omitted, lockally generates a 16-char password and returns it in the response — shown once.  **Gate.** The mailbox&#39;s domain must already be registered AND verified for this tenant (via &#x60;/v1/domains&#x60; + &#x60;/v1/domains/{domain}/verify&#x60;).  **Idempotent.** Re-posting the same email returns the existing mailbox UNTOUCHED — password is NOT regenerated. To change a password, use PATCH instead. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1MailboxesPostTest() throws ApiException {
        V1MailboxesPostRequest v1MailboxesPostRequest = null;
        Mailbox response = api.v1MailboxesPost(v1MailboxesPostRequest);
        // TODO: test validations
    }

    /**
     * List all vacation responders
     *
     * Returns every vacation responder for the calling tenant.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1VacationGetTest() throws ApiException {
        V1VacationGet200Response response = api.v1VacationGet();
        // TODO: test validations
    }

}
