/*
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lockally.sdk;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.nio.charset.StandardCharsets;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    static {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.APIKey.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ActivateAddOn200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.AddCalendarMemberRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.AddContactListMemberRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.AddOn.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.AddSharedMemberRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.Admin.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.AdminFull.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.Alias.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.AuditEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.BatchLookupPublicKeys200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.BatchLookupPublicKeys200ResponseDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.BatchResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.BillingStatus.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.Calendar.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CalendarEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CalendarIntegration.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CalendarMember.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CalendarPolicies.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.Contact.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ContactList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CreateBillingCheckout200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CreateBillingCheckoutRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CreateCalendarEventRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CreateCalendarIntegrationRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CreateCalendarRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CreateContactListRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CreateContactRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CreateDedicatedIPRequestRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CreateDistributionListRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CreateEncryptionKey201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CreateEncryptionKeyRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CreateEncryptionRecoveryRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CreateMigrationCredentialRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CreateMigrationCredentialRequestCredentials.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CreateMigrationRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CreateResourceRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CreateUnitsCheckout200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CreateUnitsCheckoutRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.CreateUserRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.DNSRecord.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.DedicatedIPRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.DirectoryPermissions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.DiscoverMigration202Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.DistributionListDetail.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.DistributionListSummary.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.Domain.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GALSettings.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetAddOnStatus200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetAuditSummary200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetCalendarSecurity200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetCalendarSecurity200ResponseAlertsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetCalendarSecurity200ResponseDelegatedAccessInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetCalendarSecurity200ResponseExternalSharing.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetCalendarSecurity200ResponsePublicCalendarListInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetContactList200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetContactList200ResponseMembersInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetContactLists200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetContactLists200ResponseDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetDirectoryActivity200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetDirectoryActivity200ResponseDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetDirectoryStats200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetDomainsStatus200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetDomainsStatus200ResponseDomainsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetDomainsStatus200ResponseDomainsInnerChecksInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetEncryptionKey200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetIPAssignment200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetIntegrationsSummary200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetIntegrationsSummary200ResponseApiKeysInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetIntegrationsSummary200ResponseWebhooksInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetSecurity200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetSecurity200ResponseAlertsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetSecurity200ResponseStatsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetStorage200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetStorage200ResponseTopMailboxesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetStorage200ResponseTopMessagesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.GetUserInsights200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.HealthzGet200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ListAddOns200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ListCalendarEvents200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ListCalendarIntegrations200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ListCalendarMembers200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ListCalendars200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ListContactLists200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ListContacts200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ListDedicatedIPRequests200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ListDistributionLists200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ListMigrationCredentials200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ListMigrationEvents200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ListMigrationMailboxes200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ListMigrations200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ListResources200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ListSharedMembers200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ListUsers200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.Mailbox.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.MapMigrationRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.MapMigrationRequestMappingsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.Message.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.MessageDetail.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.MessageStats.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.MessageStatsCounts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.MessageStatsRates.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.MessageStatsWindow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.Migration.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.MigrationCredential.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.MigrationEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.MigrationMailbox.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.MigrationProgress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.MigrationProgressMailboxesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.MigrationSettings.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.PlanCatalogEntry.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.Problem.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ReplaceDistributionListMembers200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.ReplaceDistributionListMembersRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.Resource.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.RotateEncryptionKeyRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.SendMessage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.SharedMember.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.SignupRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.StartMigration202Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.Suppression.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.Template.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.TemplateInput.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.Tenant.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.UnitBundle.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.UpdateCalendarEventRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.UpdateCalendarIntegrationRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.UpdateCalendarMemberRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.UpdateCalendarPoliciesRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.UpdateCalendarRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.UpdateContactListRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.UpdateContactRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.UpdateDirectoryPermissionsRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.UpdateGALSettingsRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.UpdateMigrationMailboxRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.UpdateMigrationRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.UpdateResourceRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.UpdateUserRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.User.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.UserEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1AdminLoginPost200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1AdminLoginPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1AdminMeGet200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1AdminsGet200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1AdminsIdPatchRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1AdminsPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1AliasesGet200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1AliasesPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1ApiKeysGet200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1ApiKeysPost201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1ApiKeysPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1DomainsGet200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1DomainsPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1InboxesMailboxMessagesPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1MailboxesEmailExportPost201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1MailboxesEmailPatchRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1MailboxesEmailVacationPutRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1MailboxesGet200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1MailboxesPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1MessagesGet200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1SendBatchPost200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1SendBatchPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1SendPost202Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1SendPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1SendPostRequestAttachmentsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1SuppressionsGet200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1SuppressionsPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1TemplatesGet200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1UsageGet200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1VacationGet200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1WebhooksGet200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1WebhooksIdPatchRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.V1WebhooksPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.VacationParams.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.VacationResponder.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.lockally.sdk.model.Webhook.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
    * Deserialize the given JSON InputStream to a Java object.
    *
    * @param <T>         Type
    * @param inputStream The JSON InputStream
    * @param returnType  The type to deserialize into
    * @return The deserialized Java object
    */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(InputStream inputStream, Type returnType) throws IOException {
        try (InputStreamReader reader = new InputStreamReader(inputStream, StandardCharsets.UTF_8)) {
        if (isLenientOnJson) {
            // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
            JsonReader jsonReader = new JsonReader(reader);
            jsonReader.setLenient(true);
            return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(reader, returnType);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
