/*
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lockally.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V1UsageGet200Response
 */
public class V1UsageGet200ResponseTest {
    private final V1UsageGet200Response model = new V1UsageGet200Response();

    /**
     * Model tests for V1UsageGet200Response
     */
    @Test
    public void testV1UsageGet200Response() {
        // TODO: test V1UsageGet200Response
    }

    /**
     * Test the property 'mailboxesActive'
     */
    @Test
    public void mailboxesActiveTest() {
        // TODO: test mailboxesActive
    }

    /**
     * Test the property 'mailboxesTotal'
     */
    @Test
    public void mailboxesTotalTest() {
        // TODO: test mailboxesTotal
    }

    /**
     * Test the property 'domainsVerified'
     */
    @Test
    public void domainsVerifiedTest() {
        // TODO: test domainsVerified
    }

    /**
     * Test the property 'domainsTotal'
     */
    @Test
    public void domainsTotalTest() {
        // TODO: test domainsTotal
    }

    /**
     * Test the property 'messagesSentLast60s'
     */
    @Test
    public void messagesSentLast60sTest() {
        // TODO: test messagesSentLast60s
    }

    /**
     * Test the property 'messagesSentTodayUtc'
     */
    @Test
    public void messagesSentTodayUtcTest() {
        // TODO: test messagesSentTodayUtc
    }

    /**
     * Test the property 'messagesSentLast30d'
     */
    @Test
    public void messagesSentLast30dTest() {
        // TODO: test messagesSentLast30d
    }

    /**
     * Test the property 'bytesStored'
     */
    @Test
    public void bytesStoredTest() {
        // TODO: test bytesStored
    }

    /**
     * Test the property 'rateCapPerMin'
     */
    @Test
    public void rateCapPerMinTest() {
        // TODO: test rateCapPerMin
    }

    /**
     * Test the property 'dailyMsgQuota'
     */
    @Test
    public void dailyMsgQuotaTest() {
        // TODO: test dailyMsgQuota
    }

    /**
     * Test the property 'webhooksTotal'
     */
    @Test
    public void webhooksTotalTest() {
        // TODO: test webhooksTotal
    }

    /**
     * Test the property 'webhooksPaused'
     */
    @Test
    public void webhooksPausedTest() {
        // TODO: test webhooksPaused
    }

    /**
     * Test the property 'generatedAt'
     */
    @Test
    public void generatedAtTest() {
        // TODO: test generatedAt
    }

}
